version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: test # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: everdawn_local
    volumes:
      # Persist data locally
      - ./db-data/:/var/lib/postgresql/data/
